### ISSUE TITLE
Shouldn't z be a Gaussian distribution? seems that in code your code you just take out the output of a hidden layer (train_z) and then you minimize the MMD of that with a prior! 

### ISSUE THREAD

**Issue by AliLotfi92** [ShengjiaZhao/MMD-Variational-Autoencoder#3]

**Comment by rojinsafavi** [comment]
Did you figure this out?

**Comment by AliLotfi92** [comment]
Nope, a similar issue is still open here:
https://github.com/ShengjiaZhao/InfoVAE/issues/1 
I should say I've not been able to reproduce the reported results after fixing this. I have the fixed version, let me know if you need that.

**Comment by ShengjiaZhao** [comment]
Hi sorry for this late reply. I haven't been up to date on looking at this repo. In the tutorial, we use a simplified implementation without adding random noise. For the version with random noise please see this file
https://github.com/ShengjiaZhao/MMD-Variational-Autoencoder/blob/master/mmd_vae_eval.py
